version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
python:
  install:
    - requirements: modules/stock_secondary_unit/doc/requirements-doc.txt
sphinx:
  configuration: modules/stock_secondary_unit/doc/conf.py
