[tox]
envlist = py310,py311,py312,py313,py314

[testenv]
changedir = {env_site_packages_dir}
extras = test
commands =
    coverage run --rcfile={toxinidir}/tox.ini --source=proteus --omit=*/tests/* -m xmlrunner discover -s proteus.tests {posargs}
commands_post =
    coverage report --rcfile={toxinidir}/tox.ini
    coverage xml --rcfile={toxinidir}/tox.ini -o {package_root}/coverage.xml
deps =
    coverage
    unittest-xml-reporting
passenv = *
setenv =
    TRYTOND_DATABASE_URI={env:TRYTOND_DATBASE_URI:sqlite://}
    DB_NAME={env:DB_NAME::memory:}

[coverage:run]
relative_files = true
