[tox]
envlist = py39,py310,py311,py312,py313

[testenv]
changedir = {toxworkdir}
extras = test
commands =
    coverage run --source=proteus --omit=*/tests/* -m xmlrunner discover -s proteus.tests {posargs}
commands_post =
    coverage report
    coverage xml
deps =
    coverage
    unittest-xml-reporting
passenv = *
setenv =
    TRYTOND_DATABASE_URI={env:TRYTOND_DATBASE_URI:sqlite://}
    DB_NAME={env:DB_NAME::memory:}
