[tox]
envlist = py310,py311,py312,py313,py314

[testenv]
changedir = {env_site_packages_dir}
commands =
    coverage run --rcfile={toxinidir}/tox.ini --source=tryton --omit=*/tests/* -m xmlrunner discover -s tryton.tests {posargs}
commands_post =
    coverage report --rcfile={toxinidir}/tox.ini
    coverage xml --rcfile={toxinidir}/tox.ini -o {package_root}/coverage.xml
deps =
    coverage
    unittest-xml-reporting
passenv = *

[coverage:run]
relative_files = true
