[tox]
envlist = {py310,py311,py312,py313,py314}-{sqlite,postgresql}

[testenv]
changedir = {env_site_packages_dir}
extras = test
commands =
    coverage run --rcfile={toxinidir}/tox.ini --source=trytond.modules.inbound_email --omit=*/tests/* -m xmlrunner discover -s trytond.modules.inbound_email {posargs}
commands_post =
    coverage report --rcfile={toxinidir}/tox.ini
    coverage xml --rcfile={toxinidir}/tox.ini -o {package_root}/coverage.xml
deps =
    coverage
    unittest-xml-reporting
    postgresql: psycopg[pool] >= 3
passenv = *
setenv =
    sqlite: TRYTOND_DATABASE_URI={env:SQLITE_URI:sqlite://}
    postgresql: TRYTOND_DATABASE_URI={env:POSTGRESQL_URI:postgresql://}
    sqlite: DB_NAME={env:DB_NAME::memory:}
    postgresql: DB_NAME={env:DB_NAME:test}

[coverage:run]
relative_files = true
