[tox]
envlist = {py310,py311,py312,py313,py314}-{sqlite,postgresql}

[testenv]
changedir = {toxworkdir}
extras = test
commands =
    coverage run --source=trytond.modules.authentication_saml --omit=*/tests/* -m xmlrunner discover -s trytond.modules.authentication_saml {posargs}
commands_post =
    coverage report
    coverage xml
deps =
    coverage
    unittest-xml-reporting
    postgresql: psycopg[pool] >= 3
passenv = *
setenv =
    sqlite: TRYTOND_DATABASE_URI={env:SQLITE_URI:sqlite://}
    postgresql: TRYTOND_DATABASE_URI={env:POSTGRESQL_URI:postgresql://}
    sqlite: DB_NAME={env:DB_NAME::memory:}
    postgresql: DB_NAME={env:DB_NAME:test}
