[tox]
envlist = py310,py311,py312,py313,py314

[testenv]
changedir = {toxworkdir}
extras = test
commands =
    coverage run --source=trytond --omit=*/tests/* -m xmlrunner discover -s trytond.tests {posargs}
    coverage run -a --source=trytond_gis --omit=*/tests/* -m xmlrunner discover -s trytond_gis.tests {posargs}
commands_post =
    coverage report
    coverage xml
deps =
    coverage
    unittest-xml-reporting
passenv = *
setenv =
    TRYTOND_DATABASE_URI={env:POSTGIS_URI:postgis://}
    DB_NAME={env:DB_NAME:test}
