version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
python:
  install:
    - requirements: modules/project_invoice/doc/requirements-doc.txt
sphinx:
  configuration: modules/project_invoice/doc/conf.py
